apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: awspug-cluster
  region: us-east-1

vpc:
  subnets:
    public:
      us-east-1a: { id: subnet-09c542da6deb29ef7 }
      us-east-1b: { id: subnet-01bfad3d1bfcd645e }
      us-east-1a: { id: subnet-0c4e54d5507c6744d }
      us-east-1b: { id: subnet-03a9c7c067743c15f }


nodeGroups:
  - name: ng-1
    instanceType: t3.large
    desiredCapacity: 2
    volumeSize: 80
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
  - name: ng-2
    instanceType: t3.large
    desiredCapacity: 2
    volumeSize: 100
    ssh:
      publicKeyPath: ~/.ssh/id_rsa.pub
