apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: awspug-cluster
  region: us-east-1

vpc:
  subnets:
    public:
      us-east-1a: { id: subnet-0361b32648557f0aa }
      us-east-1b: { id: subnet-0065ffdd0a57cee53 }
      us-east-1c: { id: subnet-08a73b70f170c826e }
      us-east-1d: { id: subnet-09f402f5435a7d24e }


nodeGroups:
  - name: ng-1
    instanceType: t3.large
    desiredCapacity: 2
    volumeSize: 80
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
  - name: ng-2
    instanceType: t3.large
    desiredCapacity: 2
    volumeSize: 100
    ssh:
      publicKeyPath: ~/.ssh/id_rsa.pub
