apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: awspug-cluster
  region: us-east-1

vpc:
  cidr: 10.1.0.0/16
  publicAccessCIDRs: ["151.199.255.83/32"]
  clusterEndpoints:
    privateAccess: true
    publicAccess: true
  
  subnets:
    public:
      us-east-1a: { id: subnet-05654956edbb1a019 }
      us-east-1b: { id: subnet-04d9b71c6bb11a9d7 }
      us-east-1c: { id: subnet-0a8a9691e8fc6c508 }
      us-east-1d: { id: subnet-0f0305a02c27ab53e }


nodeGroups:
  - name: ng-1
    instanceType: t3.large
    desiredCapacity: 1
    volumeSize: 80
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
      enableSsm: true
  - name: ng-2
    instanceType: t3.medium
    desiredCapacity: 2
    volumeSize: 100
    ssh:
       publicKeyPath: ~/.ssh/id_rsa.pub
       enableSsm: true

cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]
